Ebbusiness/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('EbbusinessApp.urls')),
    

]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

EbbusinessApp/urls.py
from django.conf.urls import url
from EbbusinessApp.views import CreatePopUpView
from EbbusinessApp.views import index
from EbbusinessApp.views import a_empresa
from EbbusinessApp.views import nossos_planos
from EbbusinessApp.views import fale_conosco
from EbbusinessApp.views import contratar
from EbbusinessApp.views import salvo

urlpatterns = [
    url(r'^index/', index, name='index'),
    url(r'^a_empresa/', a_empresa, name='a_empresa'),
    url(r'^nossos_planos/', nossos_planos, name='nossos_planos'),
    url(r'^fale_conosco/', fale_conosco, name='fale_conosco'),
    url(r'^contratar/', contratar, name='contratar'),
    url(r'^salvo/', salvo, name='salvo'),
    url(r'^create/', CreatePopUpView.as_view(), name='abrir-contrato'),
    url(r'', index, name='index'),
]

EbbusinessApp/models.py
from django.db import models

# Create your models here.

class Planos(models.Model):
    planos = models.CharField(max_length=100)

    def __str__(self):
        return self.planos

class Assinaturas(models.Model):
    assinaturas = models.CharField(max_length=100)

    def __str__(self):
        return self.assinaturas

class Empresas(models.Model):
    nomeEmpresa = models.CharField(max_length=100)
    nomeContato = models.CharField(max_length=100)
    numeroCnpj = models.CharField(max_length=18, primary_key=True)
    enderecoRua = models.CharField(max_length=100)
    enderecoNumero = models.CharField(max_length=10)
    enderecoComplemento = models.CharField(max_length=100, blank=True)
    cidade = models.CharField(max_length=100)
    numeroCep = models.CharField(max_length=10)
    numetoTelefone = models.CharField(max_length=14)
    email = models.EmailField()
    plano = models.ForeignKey(Planos, on_delete=models.CASCADE)
    assinatura = models.ForeignKey(Assinaturas, on_delete=models.CASCADE)    
    estadosBrasileiros = [
    ('', 'Escolher...'),
    ('AC', 'Acre'),
    ('AL', 'Alagoas'),
    ('AP', 'Amapá'),
    ('AM', 'Amazonas'),
    ('BA', 'Bahia'),
    ('CE', 'Ceará'),
    ('DF', 'Distrito Federal'),
    ('ES', 'Espírito Santo'),
    ('GO', 'Goiás'),
    ('MA', 'Maranhão'),
    ('MT', 'Mato Grosso'),
    ('MS', 'Mato Grosso do Sul'),
    ('MG', 'Minas Gerais'),
    ('PA', 'Pará'),
    ('PB', 'Paraíba'),
    ('PR', 'Paraná'),
    ('PE', 'Pernambuco'),
    ('PI', 'Piauí'),
    ('RJ', 'Rio de Janeiro'),
    ('RN', 'Rio Grande do Norte'),
    ('RS', 'Rio Grande do Sul'),
    ('RO', 'Rondônia'),
    ('RR', 'Roraima'),
    ('SC', 'Santa Catarina'),
    ('SP', 'São Paulo'),
    ('SE', 'Sergipe'),
    ('TO', 'Tocantins'),
    ]
    estados = models.CharField(max_length=2, choices=estadosBrasileiros, default='')

class Contato(models.Model):
    contatoNome = models.CharField(max_length=100)
    contatoEmail = models.EmailField()
    contatoMensagem = models.TextField()

EbbusinessApp/forms.py
from django import forms
from .models import Empresas, Contato
from bootstrap_modal_forms.forms import BSModalForm

class ContratoForm(BSModalForm):
    class Meta:
        model = Empresas
        fields = ['nomeEmpresa', 'numeroCnpj', 'plano', 'assinatura',]
        labels = {
            'nomeEmpresa':'Empresa',            
            'numeroCnpj':'CNPJ',            
            'plano':'Planos',
            'assinatura':'Assinaturas',
        }

class DadosEmpresas(forms.ModelForm):
    confirmaInformacao = forms.BooleanField(label='Confirmo que todas as informações acima são verdadeiras.')
    confirmaContrato = forms.BooleanField(label='Confirmo que li e estou de acordo com os termos do contrato.')
    class Meta:        
        model = Empresas
        fields = ('nomeEmpresa', 'nomeContato',
        'numeroCnpj', 'enderecoRua', 'enderecoNumero', 'enderecoComplemento',
        'cidade', 'estados', 'numeroCep', 'numetoTelefone', 'email', 'plano', 'assinatura',)
        labels = {
            'nomeEmpresa':'Empresa',
            'nomeContato':'Nome para contato',
            'numeroCnpj':'CNPJ',
            'enderecoRua':'Rua',
            'enderecoNumero':'Número',
            'enderecoComplemento':'Complemento',
            'cidade':'Cidade',
            'estados':'Estado',
            'numeroCep':'CEP',
            'numetoTelefone':'Telefone',
            'email':'Email',
            'plano':'Planos',
            'assinatura':'Assinaturas',
        }
        
class DadosContato(forms.ModelForm):
    class Meta:
        model = Contato
        fields = ('contatoNome', 'contatoEmail', 'contatoMensagem', )
        labels = {
            'contatoNome':'Nome',
            'contatoEmail':'Email',
            'contatoMensagem':'Mensagem',
        }
        widgets = {
          'contatoMensagem': forms.Textarea(attrs={'rows':4, 'cols':15}),
        }

EbbusinessApp/views.py
from django.shortcuts import render, get_object_or_404, redirect

from django.http import HttpResponse
from django.urls import reverse_lazy
from .forms import DadosEmpresas, ContratoForm, DadosContato
from bootstrap_modal_forms.generic import BSModalCreateView

class CreatePopUpView(BSModalCreateView):
    template_name = 'contrato.html'
    form_class = ContratoForm    


def index(request):
    return render(request, 'index.html')

def a_empresa(request):
    return render(request, 'a_empresa.html')

def nossos_planos(request):
    return render(request, 'nossos_planos.html')

def contratar(request):
    dados = {}
    if request.method == 'POST':
        form = DadosEmpresas(request.POST)
        if form.is_valid():
            form.save()
        dados['data'] = form           
        return render(request, 'salvo_contrato.html', dados)    
    form = DadosEmpresas()
    return render(request, 'contratar.html', {'form':form})

def fale_conosco(request):
    if request.method == 'POST':
        form = DadosContato(request.POST)
        if form.is_valid():
            form.save()
            return render(request, 'salvo_mensagem.html')
    
    form = DadosContato()
    return render(request, 'fale_conosco.html', {'form':form})

def salvo(request):
    return render(request, 'salvo_contrato.html')

EbbusinessApp/templates/a_empresa.html
{% extends 'base.html' %}
{% block title %}
EBBUSINESS
{% endblock title %}
{% block content %}
<header>   
  <nav class="navbar navbar-expand-lg navbar-dark"style="background-color: rgba(0, 0, 0, .5)"; >
    <a class="navbar-brand" href="#">EBBUSINESS</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Alterna navegação">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
                <a class="nav-link" href="{% url 'index' %}">Home</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'a_empresa' %}">A empresa</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'nossos_planos' %}">Nossos Planos</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'contratar' %}">Contratar</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'fale_conosco' %}">Fale conosco</a>
            </li>
      </ul>
    </div>
  </nav>   
</header>


<br/>
<br/>
<div id="titulo_a_empresa">
  <p>EBBUSINESS</p>
</div>


<br/>
<br/>



<div id="cards_a_empresa">
  <div class="card text-white bg-secondary col-xl-12" style="max-width: 65rem;">
    <div class="card-header"><h4><strong>Quem somos</strong></h4></div>
    <div class="card-body">
    <p>A Ebbusiness foi fundada no ano de 2019 por um grupo de alunos empreendedores da Fatec Indaiatuba, com o 
    objetivo de se tornar pioneira no campo de viagens de negócios.</p>
    <p>Situada na cidade de Indaiatuba, interior de São Paulo a Ebbusiness atende a empresas de todo 
    território nacional.</p>
    </div>
  </div>


  <br/>
  <br/>
  <br/>


  <div class="card-group">
    <div class="card text-white bg-info col-lg-12" style="max-width: 18rem;">
      <div class="card-header"><h4><strong>Missão</strong></h4></div>
      <div class="card-body">
        <p><h2></h2>Facilitar as viagens a negócios.</p>
      </div>
    </div>
    <div class="card text-white bg-success col-lg-12" style="max-width: 18rem;">
      <div class="card-header"><h4><strong>Visão</strong></h4></div>
      <div class="card-body">
        <p>Tornar-se a maior prestadora de serviços de compra/reversa para viagens a negócio.</p>
      </div>
    </div>
    <div class="card text-white bg-primary col-lg-12" style="max-width: 18rem;">
      <div class="card-header"><h4><strong>Valores</strong></h4></div>
      <div class="card-body">
        <p><h2></h2>Ética;<br/>Compromisso;<br/>Comprometimento;<br/>Eficiência;<br/>Qualidade.</p>
      </div>
    </div>
  </div>
</div>


<br/>
<br/>
<br/>
<br/>
<br/>


<div class="rodape"> 
  <footer>
    <p>Ebbusiness</p>
    <p>Endereço: Rua Indaiatuba, nº 00 Jardim Indaiatuba , Indaiatuba - SP</p>
    <p>Telefone: 1111-1111 Email: ebbusiness@ebusiness.com.br</p>
  </footer>
</div>
{% endblock %}

EbbusinessApp/templates/base.html
<!DOCTYPE html>
<html lang="en">


<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link href="{% static "css/style.css" %}" rel="stylesheet">
    <link href="{% static  "css/css/bootstrap.min.css" %}" rel="stylesheet">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <script src="{% static 'js/scripts.js' %}"></script>
    <script src="{% static 'js/jquery-3.5.1.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/bootstrap.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/jquery.mask.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/jquery.bootstrap.modal.forms.min.js' %}"></script>

    <script type="text/javascript">
        $(document).ready(function(){
            $(".abrir-contrato").modalForm({
                formURL: "{% url 'abrir-contrato' %}"
            })
            $("#id_cpf").mask("000.000.000-00")
            $("#id_numeroCnpj").mask("00.000.000/0000-00")
            $("#id_numetoTelefone").mask("(00) 0000-0000")            
            $("#id_numeroCep").mask("00.000-000")
        })
        </script>
 
    <title>
        {% block title %}
        {% endblock %}
    </title>
</head>


<body id="body">
{% block content %}
{% endblock %}
<!--<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>-->
</body>


</html>

EbbusinessApp/templates/contratar.html
{% extends 'base.html' %}
{% block title %}
EBBUSINESS
{% endblock title %}
{% block content %}
{% load crispy_forms_tags %}
{% load static %}

<header>   
  <nav class="navbar navbar-expand-lg navbar-dark"style="background-color: rgba(0, 0, 0, .5)"; >
    <a class="navbar-brand" href="#">EBBUSINESS</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Alterna navegação">
    <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" href="{% url 'index' %}">Home</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'a_empresa' %}">A empresa</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'nossos_planos' %}">Nossos Planos</a>
        </li>
        <li class="nav-item active">
            <a class="nav-link" href="{% url 'contratar' %}">Contratar</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'fale_conosco' %}">Fale conosco</a>
        </li>
      </ul>
    </div>
  </nav>   
</header>

<br/>
<br/>
<br/>
<br/>


<div id="tituloInformativoContratar">
  <p>PARA CONTRATAR UM DE NOSSOS PLANOS PREENCHA O FORMULÁRIO ABAIXO.</p>
</div>


<br/>
<br/>
<br/>
<br/>


<div id="formularioContratar">

  <form method="POST">
      {% csrf_token %}
      <div class="row">
        <div class="form-group col-lg-5">
          <div class="col-formularioContratar">
            {{form.nomeEmpresa|as_crispy_field}}
          </div>                 
        </div>
        <div class="form-group col-lg-4">
          <div class="col-formularioContratar">
            {{form.nomeContato|as_crispy_field}}         
          </div>          
        </div>
        <div class="form-group col-lg-3">
          <div class="formularioContratar">
            {{form.numeroCnpj|as_crispy_field}}            
          </div>          
        </div>
      </div>
      <div class="row">
        <div class="form-group col-lg-5">
          <div class="formularioContratar">
            {{form.enderecoRua|as_crispy_field}}
          </div>          
        </div>
        <div class="form-group col-lg-4">
          <div class="formularioContratar">
            {{form.enderecoNumero|as_crispy_field}}
          </div>          
        </div>
        <div class="form-group col-lg-3">
          <div class="formularioContratar">
            {{form.enderecoComplemento|as_crispy_field}}
          </div>          
        </div>
      </div>
      <div class="row">
        <div class="form-group col-lg-5">
          <div class="formularioContratar">
            {{form.cidade|as_crispy_field}}
          </div>          
        </div>
        <div class="form-group col-lg-4">
          <div class="formularioContratar">
            {{form.estados|as_crispy_field}}
          </div>
        </div>
        <div class="form-group col-lg-3">
          <div class="formularioContratar">
            {{form.numeroCep|as_crispy_field}}
          </div>          
        </div>
      </div>
      <div class="row">
        <div class="form-group col-lg-3">
          <div class="formularioContratar">
            {{form.numetoTelefone|as_crispy_field}}
          </div>          
        </div>
        <div class="form-group col-lg-3">
          <div class="formularioContratar">
            {{form.email|as_crispy_field}}
          </div>          
        </div>
        <div class="form-group col-lg-3">
          <div class="formularioContratar">
            {{form.plano|as_crispy_field}}
          </div>          
        </div>
        <div class="form-group col-lg-3">
          <div class="formularioContratar">
            {{form.assinatura|as_crispy_field}}
          </div>
          <div class="modal fade" tabindex="-1" role="dialog" id="modal">
            <div class="modal-dialog" role="document">
              <div class="modal-content"></div>
            </div>
          </div>         
        </div>        
      </div>                
      <br/>      
      <div class="row">
        <div class="form-group col-lg-6">
          <div class="formCheck">          
            {{form.confirmaInformacao|as_crispy_field}}
            <label class="form-check-label" for="gridCheck">
              *Campos obrigatórios.
              </label>
          </div>
        </div>
        <div class="form-group col-lg-6">
          <div class="formCheck">          
            {{form.confirmaContrato|as_crispy_field}}
            <a href="#abrir-contrato" class="abrir-contrato">Clique aqui para acessar os termos do contrato.</a>          
          </div>          
        </div>
      </div>
      <br/>
      <button type="submit" class="btn btn-primary">Contratar</button>
    </form>
</div>


<div class="rodape"> 
  <footer>
    <p>Ebbusiness</p>
    <p>Endereço: Rua Indaiatuba, nº 00 Jardim Indaiatuba , Indaiatuba - SP</p>
    <p>Telefone: 1111-1111 Email: ebbusiness@ebusiness.com.br</p>
  </footer>
</div>

{% endblock %}

EbbusinessApp/templates/contrato.html
{% extends 'base.html' %}
{% block content %}
{% load crispy_forms_tags %}
{% load static %}
<style>
    /* CSS imbutido no HTML para identar tags com a CLASS INDENT*/
    .indent {
        margin-left: 40px;
    }
</style>

<form method="post" action="">
    {% csrf_token %}
    <div class="modal-header">
        <h2 class="modal-title">Termos do contrato</h2>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <div class="modal-body">
        <div>
            <p>
                <b class="indent">Contratante:</b> Qualquer usuário que realizou o cadastro para solicitar um contrato de prestação de serviços relacionados ao gerenciamento de viagens empresariais;<br>
                
                <b class="indent">Contratado:</b> Ebbusiness, empresa brasileira, portadora do CNPJ nº xx.xxx.xxx/xxx-xx, situada no endereço: Rua Indaiatuba, nº 00 Jardim Indaiatuba , Indaiatuba - SP;<br>
                
                <span class="indent">Pelo presente instrumento particular de prestação de serviços de gerenciamento de viagens empresariais, têm entre si justos e acordados quanto segue: </span>
                
        <H4>DO OBJETO DO CONTRATO</H4>
                <b class="indent">CLÁUSULA 1ª:</b> O presente instrumento, tem como objeto, a prestação de serviços relacionados ao gerenciamento de viagens empresariais.<br>
                <b class="indent">CLÁUSULA 2ª:</b> O contratado executará os serviços diretamente a contratante ou aos funcionários por este indicados.
                DOS SERVIÇOS<br>
                <b class="indent">CLÁUSULA 3ª:</b> O contratado prestará os seguintes serviços que foram selecionados pelo contratante no site da Ebbusiness, entre os seguintes planos: Classical, Executive ou First Class.<br>
            
        <h4>DOS HONORÁRIOS</h4>
            <b class="indent">CLÁUSULA 4ª:</b> O contratado perceberá o valor integral selecionado pelo contratante no site da Ebbusiness, sendo o valor em Reais que serão cobrados conforme selecionado no site da Ebbusiness, sendo, mensal, semestral ou anual.<br>
            <b class="indent">CLÁUSULA 5ª:</b> Fica estabelecido que são obrigações da Contratante:<br>
                a) Efetuar o pagamento, de acordo como estabelecido na cláusula quarta do presente contrato.<br>
                b) Fornecer para o Contratado, cópias dos contratos efetivamente realizados.<br>
                c) Fornecer ao contratado, materiais e informações, indispensáveis ao seu serviço, facilitando a prospecção dos negócios.<br>
                d) Fica vedado ao contratante, negociar abatimentos, descontos ou dilações de prazo para o pagamento o execução dos serviços, sem o prévio conhecimento e autorização do contratado. <br>
            <b class="indent">CLÁUSULA 6ª:</b> Fica estabelecido as seguintes obrigações do Contratado:<br>
                a) Cumprir o estipulado nos termos do presente instrumento contratual. <br>
                b) Obedecer as instruções da contratante, sobre os termos dos serviços à serem prestados aos clientes.<br>
                c) Prestar informações à contratante, sempre que esta lhe solicitar, informando sobre a execução de seus serviços e demais detalhes sobre a execução de suas atividades. <br>
                d) Não revelar detalhes de suas atividades a terceiros, bem como, informações sobre seus clientes.<br>
                e) Não intermediar abatimentos, descontos, ou dilação sem expressa autorização da contratante. <br>
            <b class="indent">CLÁUSULA 7ª:</b> São motivos para que o Contratante rescinda o presente instrumento:<br>
                a) Desídia do contratado no cumprimento das obrigações assumidas para com a contratante e terceiros. <br>
                b) Praticar atos, que atinjam a imagem comercial da contratante perante terceiros.<br>
                c) Deixar de cumprir o contratado, qualquer das cláusulas dispostas no presente instrumento.<br>
            <b class="indent">CLÁUSULA 8ª:</b> São motivos para que o Contratado rescinda o presente instrumento:<br>
                a) Solicitar a Contratante, atividade que exceda o previsto neste instrumento de contrato.<br>
                b) Deixar a contratante de observar quaisquer obrigações que conste no presente contrato.<br>
                c) Deixar a Contratante de cumprir com o disposto na cláusula terceira deste contrato.<br>
                d) Por motivos de força maior. <br>
            <b class="indent">CLÁUSULA 9ª:</b> O presente contrato, terá vigência no prazo indicado pelo tipo de assinatura, seja ela mensal, semestral ou anula, sendo renovado automaticamente ao final do período escolhido, porém, havendo interesse em sua rescisão, a parte interessada notificará a parte contraria, por escrito, com antecedência mínima de trinta (30) dias.<br>
            
            <p>
            <span class="indent">PARÁGRAFO ÚNICO:</span> A rescisão do presente instrumento de contrato, não extingue os direitos e obrigações que as partes tenham entre si a para com terceiros.</p>
            
        <h4>DO FORO</h4>
            <b class="indent">CLÁUSULA 10ª:</b> As parte elegem o Foro da Comarca de Campinas - SP, para dirimir judicialmente as controvérsias inerentes do presente contrato. Uma cópia do contrato, com as informações oficiais do contratante será enviada no e-mail fornecido no ato da contratação do serviço. Esse contrato deve estar assinado, em 2 (duas) vias de igual forma, teor, na presença de testemunhas, e devolvido à Ebbusiness digitalmente para arquivamento no nosso sistema.
            </p>
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>        
      </div> 
</form>
    
{% endblock %}

EbbusinessApp/templates/fale_conosco.html
{% extends 'base.html' %}
{% block title %}
EBBUSINESS
{% endblock title %}
{% block content %}
{% load crispy_forms_tags %}
{% load static %}

<header>    
    <nav class="navbar navbar-expand-lg navbar-dark"style="background-color: rgba(0, 0, 0, .5)"; >
        <a class="navbar-brand" href="#">EBBUSINESS</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Alterna navegação">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'index' %}">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'a_empresa' %}">A empresa</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'nossos_planos' %}">Nossos Planos</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'contratar' %}">Contratar</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'fale_conosco' %}">Fale conosco</a>
            </li>
          </ul>
        </div>
      </nav>   
</header>

<br/>
<br/>
<br/>
<br/>
 

<div id="tituloInformativoFaleConosco">
  <p>PREENCHA O FORMULÁRIO ABAIXO PARA ENVIAR-NOS SUA MENSAGEM.</p>
</div>


<br/>
<br/>
<br/>
<br/> 


<div id="FormularioFaleConosco">
  <form method="POST">
    {% csrf_token %}
    <div class="row">
      <div class="form-group col-lg-8">
        <div class="col-formularioFaleConosco">
          {{form.contatoNome|as_crispy_field}}
        </div>        
      </div>
      <div class="form-group col-lg-4">
        <div class="col-formularioFaleConosco">
          {{form.contatoEmail|as_crispy_field}}
        </div>
      </div>
    </div>
    <div class="campoMensagem">
      {{form.contatoMensagem|as_crispy_field}}    
    </div>      
    <div class="row">
      <div class="form-group col-lg-6">
        <div class="formCheck">            
          <label class="form-check-label" for="gridCheck">
          *Campos obrigatórios.
          </label>
        </div>
      </div>
    </div>
    <br/>
    <button type="submit" class="btn btn-primary">Enviar</button>
  </form>
</div>


<div class="rodape"> 
  <footer>
    <p>Ebbusiness</p>
    <p>Endereço: Rua Indaiatuba, nº 00 Jardim Indaiatuba , Indaiatuba - SP</p>
    <p>Telefone: 1111-1111 Email: ebbusiness@ebusiness.com.br</p>
  </footer>
</div>

{% endblock %}